#!/usr/bin/env bash
#
# bootstrap installs things.

# 改变当前目录到脚本所在目录的父目录。
cd "$(dirname "$0")/.."

# 设置变量DOTFILES_ROOT为当前目录的绝对路径。
DOTFILES_ROOT=$(pwd -P)

# 如果有任何语句返回非零值，则退出脚本。
set -e

echo ''

# 定义了一个info函数，用于以蓝色文本输出信息。
info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

# 定义了一个user函数，用于以黄色文本提示用户输入信息。
user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

# 定义了一个success函数，用于以绿色文本表示操作成功。
success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

# 定义了一个fail函数，用于以红色文本表示操作失败，并退出脚本。
fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

# 定义了setup_gitconfig函数，该函数用于配置GIT环境。
# 如果本地不存在gitconfig.local.symlink文件，
# 则会询问用户github的用户名和邮箱，并据此生成配置文件。
setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    success 'gitconfig'
  fi
}

# 定义了link_file函数，用于创建两个文件之间的符号链接。
# 如果目标文件已存在，则会询问用户是覆盖、备份还是跳过。
link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

#定义了install_dotfiles函数，该函数查找所有.symlink文件并创建到用户家目录的符号链接。
install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

setup_gitconfig
install_dotfiles

# If we're on a Mac, let's install and setup homebrew.
if [ "$(uname -s)" == "Darwin" ]
then
  info "installing dependencies"
  if source bin/dot | while read -r data; do info "$data"; done
  then
    success "dependencies installed"
  else
    fail "error installing dependencies"
  fi
fi

echo ''
echo '  All installed!'
